name: release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate realise version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
          token:  ${{ secrets.GIT_ACCESS_TOKEN }}


      - name: Create Release Branch
        run: |
          git config --global user.email "stefan.spiska@vitagroup.ag"
          git config --global user.name "stefan.spiska"
          git checkout -b release/v${VERSION}
          mvn versions:set -DnewVersion=${VERSION} -DprocessAllModules=true
          git add -A
          git commit -m "release ${VERSION}: updated version to${VERSION}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_ACCESS_TOKEN }}
          branch: release/v${VERSION}

      - name: Wait for ci pipeline
        run: |
          STATUS="pending"
          COMMIT=$(git rev-parse HEAD)
          echo "$COMMIT"
          while [ "$STATUS" == "pending" ]
          do
           STATUS=$(gh api /repos/stefanspiska/openEHR_SDK/commits/"${COMMIT}"/status -q .state)
          echo "$STATUS"
          sleep 10
          STATUS="success"
          done
          echo "$STATUS"
          if [ "$STATUS" != "success" ]
           then exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
