name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate realise version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token:  ${{ secrets.PERSONAL_ACCESS_TOKEN }}


      - name: Create Release Branch
        run: |
          git config --global user.email "bot@ehrbase.org"
          git config --global user.name "bot"
          git checkout -b release/v${VERSION}
          mvn versions:set -DnewVersion=${VERSION} -DprocessAllModules=true
          sed -i 's/\[unreleased\]/${VERSION}/' CHANGELOG.md
          git add -A
          git commit -m "release ${VERSION}: updated version to ${VERSION}"
          git push -u origin release/v${VERSION}     

      - name: Wait for ci pipeline
        run: |
          STATUS="pending"
          COMMIT=$(git rev-parse HEAD)
          echo "$COMMIT"
          while [ "$STATUS" == "pending" ]
          do
           STATUS=$(gh api /repos/stefanspiska/openEHR_SDK/commits/"${COMMIT}"/status -q .state)
          echo "$STATUS"
          sleep 10
          done
          echo "$STATUS"
          if [ "$STATUS" != "success" ]
           then exit 1
          fi
      - name: Merge into Main
        run: |
          git checkout master
          git pull
          git merge --no-ff release/v${VERSION}
          git push

      - name: Merge into dev
        run: |
          ARRAY_VERSION=( ${VERSION//./ } )
          git checkout  release/v${VERSION}
          NEXT_VERSION= ${ARRAY_VERSION[0]}.$(expr ${ARRAY_VERSION[1]}+1).0-SNAPSHOT
          mvn versions:set -DnewVersion=${NEXT_VERSION} -DprocessAllModules=true
          sed -i '5i ## [unreleased]\n ### Added \n ### Fixed \n' CHANGELOG.md
          git commit -m " updated version to ${NEXT_VERSION}"
          git checkout develop
          git pull
          git merge --no-ff release/v${VERSION}
          git push

