# Ads the results of a workflow as a commit status
name: Set test status

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  set_status:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Create status
        run: |
         gh api  repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
          -H 'content-type: application/json' \
          -f body '{
            "state": "${{ github.event.workflow_run.conclusion }}",
            "context": "${{ github.event.workflow_run.event }}.${{ github.event.workflow_run.id}}",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }'
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
